version: "3.8"

services:
  api:
    build: .
    restart: always
    depends_on:
      - db
      - jobe
    ports:
      - 80:80
    environment:
      - MONGO_DB=mongodb://db/parsons
      - PORT=80
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  jobe:
    image: trampgeek/jobeinabox
    ports:
      - 4000:80
