version: "3.8"

name: parsons
services:
  api:
    build: .
    restart: always
    depends_on:
      - db
      - jobe
    ports:
      - 3001:3001
    environment:
      - MONGO_DB=mongodb://db/parsons
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  jobe:
    image: trampgeek/jobeinabox
    ports:
      - 4000:80
