version: "3.8"

services:
  api:
    build: .
    restart: always
    depends_on:
      - db
      - jobe
    ports:
      - 3001:3001
    environment:
      - "MONGO_DB=${MONGO_URL-mongodb://db/parsons}"
      - PORT=3001
      - JOBE_URL=http://jobe
  db:
    image: mongo:latest
    restart: always
    profiles:
      - local
    ports:
      - 27017:27017
  jobe:
    image: trampgeek/jobeinabox
